### ISSUE TITLE
publish to Quicklisp or ultra lisp?

### ISSUE THREAD

**Issue by abishek** [vityafx/dotenv#1]
This is just the library I was looking for (and almost started writing from scratch). Can you publish this to quicklisp or ultralisp?

**Comment by iddm** [comment]
Yes, I will publish it for you. I'll need a few days for that.

**Comment by abishek** [comment]
Awesome, thanks!

**Comment by iddm** [comment]
I am trying to publish it in quicklisp [here](https://github.com/quicklisp/quicklisp-projects/issues/2100).

**Comment by iddm** [comment]
https://github.com/quicklisp/quicklisp-projects/commit/3f7d3530326a0b237cde91d629f2cc836c11987f Looks like it was added, can you check please?

**Comment by abishek** [comment]
Yes! it is available now. Thanks!
